import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Plus, Save, Send } from "lucide-react";
import type { EodContext, EodPriority, EodRecord, EodResponseValue, EodTemplateDefinition, EodWorkSummary } from "@mobius-ems/shared";
import { api } from "@/api/client";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { VoiceDictation } from "@/components/VoiceDictation";
import { control, healthLabels, MetricCards, metricForSource, panel, SalesSnapshot, Section, TaskCards, TemplateField } from "./EodComponents";
export interface MyReportData { employee: EodContext; update?: EodRecord; template: EodTemplateDefinition; summary: EodWorkSummary; liveSummary: EodWorkSummary }
const common = [["accomplishments", "Key outcome of the day"], ["inProgress", "Work still in progress"], ["blockers", "General blocker / support required"], ["importantNote", "Important note"], ["remarks", "Additional remarks"]] as const;
export function EmployeeReport({ date, data, canSubmit }: { date: string; data: MyReportData; canSubmit: boolean }) {
  const client = useQueryClient();
  const { employee, update, template, summary, liveSummary } = data;
  const [draft, setDraft] = useState({ accomplishments: update?.accomplishments ?? "", inProgress: update?.inProgress ?? "", nextPlan: update?.nextPlan ?? "", blockers: update?.blockers ?? "", importantNote: update?.importantNote ?? "", remarks: update?.remarks ?? "", health: update?.health ?? "ON_TRACK" as EodRecord["health"] });
  const [responses, setResponses] = useState<Record<string, EodResponseValue>>(update?.responses ?? {});
  const [priorities, setPriorities] = useState<EodPriority[]>(update?.priorities ?? []);
  const [reportedCompleted, setReportedCompleted] = useState<string>(update?.reportedCompleted?.toString() ?? "");
  const [saved, setSaved] = useState("");
  const voiceFields = [...common.map(([key, label]) => ({ key, label })), ...template.sections.flatMap(s => s.fields).filter(f => !f.source && ["TEXT", "TEXTAREA"].includes(f.type)).map(f => ({ key: `response:${f.key}`, label: f.label }))];
  const [voiceField, setVoiceField] = useState<string>("accomplishments");
  const save = useMutation({ mutationFn: (status: EodRecord["status"]) => api.put("/api/v1/eod", { ...draft, responses, priorities, reportedCompleted: reportedCompleted !== "" ? Number(reportedCompleted) : null, date, status }), onSuccess: async (_, status) => { setSaved(status === "DRAFT" ? "Draft saved. Only you can see it." : "Daily report submitted and available for review."); await client.invalidateQueries({ queryKey: ["eod"] }); } });
  const editPriority = (index: number, changes: Partial<EodPriority>) => { setSaved(""); setPriorities(current => current.map((p, i) => i === index ? { ...p, ...changes } : p)); };
  const manualText = (key: typeof common[number][0], label: string) => <label className="block text-sm font-semibold">{label}<textarea rows={3} maxLength={4000} className={control} value={draft[key]} onChange={event => { setSaved(""); setDraft({ ...draft, [key]: event.target.value }); }}/></label>;
  const completed = summary.tasks.filter(t => summary.completedTaskIds ? summary.completedTaskIds.includes(t._id) : t.completionDate && new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(t.completionDate)) === date);
  return <div className="space-y-6"><section className={`${panel} border-t-4 border-t-brand-600`}><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-xl font-semibold">{employee.firstName} {employee.lastName}</h2><p className="mt-1 text-sm text-slate-600">{employee.employeeId} · {update?.designationSnapshot?.name ?? employee.designation?.name} · {update?.departmentSnapshot?.name ?? employee.department?.name}</p><p className="mt-2 text-sm text-slate-600">Team: {update?.teamSnapshot?.name ?? employee.team?.name ?? "Not assigned"} · Manager: {update?.reportingManagerSnapshot?.name ?? (employee.reportingManager ? `${employee.reportingManager.firstName} ${employee.reportingManager.lastName}` : "Not assigned")}</p></div><span className="h-fit rounded-full bg-brand-50 px-3 py-1 text-sm font-semibold text-brand-700">{update?.status ?? "Not started"}</span></div></section>
    <Section title="Today's work snapshot" hint={`System-recorded activity for ${date} (IST). Open work reflects the source state when generated. ${update?.status === "SUBMITTED" ? "Showing your saved submission snapshot." : "Generated from Tasks and Daily Todos."}`}><MetricCards metrics={[["Assigned tasks", summary.metrics.totalAssigned], ["Completed today", summary.metrics.completed], ["In progress", summary.metrics.inProgress], ["Blocked", summary.metrics.blocked], ["In review", summary.metrics.inReview], ["Overdue", summary.metrics.overdue], ["Reopened", summary.metrics.reopened], ["Todos completed", summary.metrics.todosCompleted], ["Todos pending", summary.metrics.todosPending], ["Quality / 5", summary.metrics.averageQuality], ["On-time %", summary.metrics.onTimePercent], ["Hours variance", summary.metrics.hoursVariance]]}/><p className="mt-3 text-xs text-slate-600">Estimated {summary.metrics.estimatedHours ?? 0}h / actual {summary.metrics.actualHours ?? 0}h for completed tasks with recorded hours. Last generated {new Date(summary.generatedAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST.</p></Section>
    <Section title="Work completed"><TaskCards tasks={completed}/></Section>
    <div className="grid gap-6 xl:grid-cols-2"><Section title="Work in progress"><TaskCards tasks={summary.tasks.filter(t => ["NOT_STARTED", "IN_PROGRESS", "REOPENED", "IN_REVIEW"].includes(t.status))}/></Section><Section title="Blocked work" hint="Source blocker reasons and notes help your manager coordinate support."><TaskCards tasks={summary.tasks.filter(t => t.status === "BLOCKED")}/></Section></div>
    {!!liveSummary.commitments.length && <Section title="Previous report commitments" hint="Live task state; unlinked priorities stay pending until you provide context. No performance score is inferred."><div className="space-y-3">{liveSummary.commitments.map((p, i) => <div key={i} className="flex flex-wrap justify-between gap-2 rounded-xl border p-3 text-sm"><span>{p.expectedOutcome}</span><strong>{p.state.replaceAll("_", " ")}</strong></div>)}</div></Section>}
    <form onSubmit={event => { event.preventDefault(); save.mutate("SUBMITTED"); }} className="space-y-6"><fieldset disabled={save.isPending || !canSubmit} className="space-y-6">
      <Section title="Voice input" hint="Choose a field, dictate, and check the text before saving."><label className="text-sm font-semibold">Field to update<select className={control} value={voiceField} onChange={event => setVoiceField(event.target.value)}>{voiceFields.map(f => <option key={f.key} value={f.key}>{f.label}</option>)}</select></label><div className="mt-3"><VoiceDictation key={voiceField} disabled={save.isPending || !canSubmit} onTranscript={text => { setSaved(""); if (voiceField.startsWith("response:")) { const key = voiceField.slice(9); setResponses(current => ({ ...current, [key]: `${current[key] ?? ""}\n${text}`.trim().slice(0, 4000) })); } else setDraft(current => ({ ...current, [voiceField]: `${current[voiceField as keyof typeof current]}\n${text}`.trim().slice(0, 4000) })); }}/></div></Section>
      {summary.sales && <Section title="Sales activity" hint="CRM and lead-work records. Currency amounts remain separate."><SalesSnapshot sales={summary.sales}/></Section>}
      {template.sections.map(section => <Section key={section.key} title={section.title} hint={`${template.name} · version ${template.version}. Add context where the source records need explanation.`}><div className="grid gap-5 md:grid-cols-2">{section.fields.map(field => <TemplateField key={field.key} field={field} value={responses[field.key]} metric={metricForSource(field.source, summary)} onChange={value => { setSaved(""); setResponses({ ...responses, [field.key]: value }); }}/>)}</div></Section>)}
      <div className="grid gap-6 lg:grid-cols-2"><Section title="Key outcome" hint="Describe the result or progress; task details are already shown above.">{manualText("accomplishments", "Key outcome of the day")}<div className="mt-4">{manualText("inProgress", "Work still in progress")}</div></Section><Section title="Blockers & support"><label className="text-sm font-semibold">How is your work going?<select className={control} value={draft.health} onChange={event => { setSaved(""); setDraft({ ...draft, health: event.target.value as EodRecord["health"] }); }}>{Object.entries(healthLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="mt-4">{manualText("blockers", "General blocker / support required")}</div></Section></div>
      <Section title="Tomorrow's priorities" hint="Up to three commitments. Link a task where useful and describe the expected outcome."><div className="space-y-4">{priorities.map((priority, index) => <div key={index} className="rounded-xl border bg-slate-50 p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Priority {index + 1}</h3><Button type="button" variant="ghost" onClick={() => setPriorities(current => current.filter((_, i) => i !== index))}>Remove</Button></div><label className="block text-sm font-semibold">Expected outcome<Input className="mt-2" maxLength={500} value={priority.expectedOutcome} onChange={event => editPriority(index, { expectedOutcome: event.target.value })}/></label><div className="mt-3 grid gap-3 md:grid-cols-3"><label className="text-sm font-semibold">Linked task<select className={control} value={priority.task ?? ""} onChange={event => editPriority(index, { task: event.target.value || undefined })}><option value="">No linked task</option>{liveSummary.tasks.map(task => <option key={task._id} value={task._id}>{task.taskId} · {task.name}</option>)}{priority.task && !liveSummary.tasks.some(t => t._id === priority.task) && <option value={priority.task}>Previously linked task</option>}</select></label><label className="text-sm font-semibold">Priority<select className={control} value={priority.priority} onChange={event => editPriority(index, { priority: event.target.value as EodPriority["priority"] })}>{["LOW", "MEDIUM", "HIGH", "URGENT"].map(value => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-semibold">Expected completion<Input className="mt-2" type="date" value={priority.expectedCompletion ?? ""} onChange={event => editPriority(index, { expectedCompletion: event.target.value || undefined })}/></label></div><label className="mt-3 block text-sm font-semibold">Note<Input className="mt-2" maxLength={1000} value={priority.note ?? ""} onChange={event => editPriority(index, { note: event.target.value })}/></label></div>)}<Button type="button" variant="secondary" disabled={priorities.length >= 3} onClick={() => setPriorities(current => [...current, { priority: "HIGH", expectedOutcome: "" }])}><Plus size={16} aria-hidden="true"/>Add priority</Button>{draft.nextPlan && <label className="block text-sm font-semibold">Earlier next-day plan<textarea className={control} rows={2} maxLength={4000} value={draft.nextPlan} onChange={event => setDraft({ ...draft, nextPlan: event.target.value })}/></label>}</div></Section>
      <Section title="Additional context"><div className="grid gap-4 md:grid-cols-2">{manualText("importantNote", "Important note")}{manualText("remarks", "Additional remarks")}</div><details className="mt-4"><summary className="min-h-11 cursor-pointer text-sm font-semibold">Reported activity vs system-recorded activity</summary><p className="my-2 text-sm text-slate-600">Optional completed-task count for clarification. The system recorded {summary.metrics.completed ?? 0} completions. Differences can reflect work outside this system.</p><label className="text-sm font-semibold">Reported tasks completed<Input className="mt-2" type="number" min={0} max={10000} step={1} value={reportedCompleted} onChange={event => setReportedCompleted(event.target.value)}/></label></details></Section>
      <div className={`${panel} flex flex-wrap items-center justify-between gap-4`}><p className="max-w-xl text-sm text-slate-600">Reports support coordination and historical context. Raise urgent blockers directly with your manager.</p><div className="flex gap-3">{update?.status !== "SUBMITTED" && <Button type="button" variant="secondary" onClick={() => save.mutate("DRAFT")}><Save size={16} aria-hidden="true"/>Save draft</Button>}<Button type="submit"><Send size={16} aria-hidden="true"/>{save.isPending ? "Saving…" : update?.status === "SUBMITTED" ? "Update submission" : "Submit EOD"}</Button></div></div>
    </fieldset>{save.error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{save.error.message}</p>}{saved && <p role="status" className="text-sm font-semibold text-brand-700">{saved}</p>}</form>
    {update?.acknowledgedAt && <Section title={`Manager review · ${(update.review?.state ?? "ACKNOWLEDGED").replaceAll("_", " ")}`}><p className="whitespace-pre-wrap text-sm">{update.managerComment || "Your daily update has been acknowledged."}</p></Section>}
  </div>;
}
