import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Save, Send, Sparkles, Code2, FlaskConical, Users, Megaphone, Cog, ReceiptIndianRupee, Building2, Headphones, Palette, BriefcaseBusiness, BadgeIndianRupee } from "lucide-react";
import { EOD_REPORT_LABELS, type EodContext, type EodPriority, type EodRecord, type EodResponseValue, type EodTemplateDefinition, type EodWorkSummary } from "@mobius-ems/shared";
import { api } from "@/api/client";
import { Button } from "@/components/ui/Button";
import { VoiceDictation } from "@/components/VoiceDictation";
import { healthLabels, MetricCards, metricForSource, SalesSnapshot, TaskCards } from "./EodComponents";
import { EngineeringIntelligence } from "./EngineeringIntelligence";
import { ReportBasicInformation, ReportCard, ReportField } from "./ReportLayout";

export interface MyReportData { employee: EodContext; update?: EodRecord; template: EodTemplateDefinition; summary: EodWorkSummary; liveSummary: EodWorkSummary }
const common = [["accomplishments", "Today's Key Result"], ["inProgress", "Work Still in Progress"], ["blockers", "Challenges / Blockers"], ["importantNote", "Important Note"], ["remarks", "Additional Remarks"]] as const;
const departmentIcons = { GENERAL: BriefcaseBusiness, ENGINEERING: Code2, SALES: BadgeIndianRupee, AI_ML: FlaskConical, HR: Users, MARKETING: Megaphone, OPERATIONS: Cog, FINANCE: ReceiptIndianRupee, ADMINISTRATION: Building2, SUPPORT: Headphones, DESIGN: Palette };
export function EmployeeReport({ date, data, canSubmit }: { date: string; data: MyReportData; canSubmit: boolean }) {
  const client = useQueryClient();
  const { update, template, summary, liveSummary } = data;
  const [draft, setDraft] = useState({ accomplishments: update?.accomplishments ?? "", inProgress: update?.inProgress ?? "", nextPlan: update?.nextPlan ?? "", blockers: update?.blockers ?? "", importantNote: update?.importantNote ?? "", remarks: update?.remarks ?? "", health: update?.health ?? "ON_TRACK" as EodRecord["health"] });
  const [responses, setResponses] = useState<Record<string, EodResponseValue>>(update?.responses ?? {});
  const [priorities, setPriorities] = useState<EodPriority[]>(() => Array.from({ length: 3 }, (_, i) => update?.priorities?.[i] ?? { priority: "HIGH", expectedOutcome: "" }));
  const [reportedCompleted, setReportedCompleted] = useState(update?.reportedCompleted?.toString() ?? "");
  const [saved, setSaved] = useState("");
  const [voiceField, setVoiceField] = useState("accomplishments");
  const voiceFields = [...common.map(([key, label]) => ({ key, label })), { key: "nextPlan", label: "Main Objective for Tomorrow" }, ...template.sections.flatMap(s => s.fields).filter(f => !f.source && ["TEXT", "TEXTAREA"].includes(f.type)).map(f => ({ key: `response:${f.key}`, label: f.label }))];
  const save = useMutation({ mutationFn: (status: EodRecord["status"]) => {
    const commitments = priorities.filter(p => p.expectedOutcome.trim() || p.task || p.note || p.expectedCompletion);
    if (commitments.some(p => !p.expectedOutcome.trim())) throw new Error("Add an expected outcome for each linked priority.");
    if (status === "SUBMITTED") {
      if (!draft.accomplishments.trim() && !draft.inProgress.trim()) throw new Error("Add today's key result or work still in progress in Daily Summary.");
      if (!draft.nextPlan.trim() && !commitments.length) throw new Error("Add tomorrow's main objective or a priority.");
      if (draft.health !== "ON_TRACK" && !draft.blockers.trim()) throw new Error("Describe the risk or blocker and the support you need.");
    }
    return api.put("/api/v1/eod", { ...draft, responses, priorities: commitments, reportedCompleted: reportedCompleted !== "" ? Number(reportedCompleted) : null, date, status });
  }, onSuccess: async (_, status) => { setSaved(status === "DRAFT" ? "Draft saved. Only you can see it." : `${EOD_REPORT_LABELS[template.adapter]} EOD report submitted successfully.`); await client.invalidateQueries({ queryKey: ["eod"] }); } });
  const edit = (key: keyof typeof draft, value: string) => { setSaved(""); setDraft(current => ({ ...current, [key]: value })); };
  const editPriority = (index: number, changes: Partial<EodPriority>) => { setSaved(""); setPriorities(current => current.map((p, i) => i === index ? { ...p, ...changes } : p)); };
  const text = (key: Exclude<keyof typeof draft, "health">, label: string, rows = 3) => <label className="sales-field">{label}<textarea rows={rows} maxLength={4000} value={draft[key]} onChange={event => edit(key, event.target.value)} placeholder={`Enter ${label.toLowerCase()}`}/></label>;
  const domainSection = (index: number) => {
    const section = template.sections[index];
    return section && <ReportCard key={section.key} index={index < 2 ? index : 3} icon={index === 0 ? departmentIcons[template.adapter] : undefined} title={/^\d+\./.test(section.title) ? section.title : `${index + 1}. ${section.title}`}><div className={`report-fields ${section.fields.length === 2 ? "report-fields-two" : ""}`}>{section.fields.map(field => <ReportField key={field.key} field={field} value={responses[field.key]} metric={metricForSource(field.source, summary)} onChange={value => { setSaved(""); setResponses(current => ({ ...current, [field.key]: value })); }}/>)}</div></ReportCard>;
  };
  const number = template.sections.length;
  const metrics = summary.metrics;
  const completed = summary.tasks.filter(t => summary.completedTaskIds ? summary.completedTaskIds.includes(t._id) : t.completionDate && new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(t.completionDate)) === date);
  const signals = [
    ...(metrics.blocked ? [`${metrics.blocked} system-recorded task(s) are blocked. Add the support owner and next step.`] : []),
    ...(metrics.overdue ? [`${metrics.overdue} task(s) are overdue. Agree on a revised delivery date.`] : []),
    ...(template.adapter === "HR" && responses.pendingHrActions && !responses.pendingFollowup ? ["Pending HR actions need a follow-up owner or next step."] : []),
    ...(template.adapter === "MARKETING" && Number(responses.approvalsPending) > 0 && !responses.approvalFollowup ? ["Campaign approvals are pending. Add the approval follow-up."] : []),
    ...(template.adapter === "AI_ML" && ["FAILED", "NEEDS_ITERATION"].includes(String(responses.outcome)) && !responses.nextExperiment ? ["Record the next experiment or iteration for this evaluation outcome."] : []),
    ...(template.adapter === "SUPPORT" && Number(responses.escalations) > 0 && !responses.escalationFollowup ? ["Escalated tickets need an owner and follow-up action."] : [])
  ];
  return <div className="sales-report department-report"><form onSubmit={event => { event.preventDefault(); save.mutate("SUBMITTED"); }}><fieldset disabled={save.isPending || !canSubmit}>
    <ReportBasicInformation date={date} data={data}/>
    <div className="sales-pair">{domainSection(0)}{domainSection(1)}</div>{template.sections.slice(2).map((_, index) => domainSection(index + 2))}
    <div className="sales-pair"><ReportCard index={4} title={`${number + 1}. Challenges / Blockers`}><div className="report-fields"><label className="sales-field">Work Status<select value={draft.health} onChange={event => edit("health", event.target.value)}>{Object.entries(healthLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="report-full-field">{text("blockers", "Blocker / Support Required")}</div>{text("importantNote", "Important Note", 2)}</div></ReportCard>
    <ReportCard index={5} title={`${number + 2}. Tomorrow's Plan`}><div className="report-tomorrow"><div><h3 className="mb-2 text-sm font-medium">Top 3 Priorities</h3><div className="sales-priorities">{priorities.map((priority, index) => <div key={index}><span>{index + 1}.</span><input aria-label={`Priority ${index + 1} expected outcome`} maxLength={500} value={priority.expectedOutcome} placeholder="Enter expected outcome" onChange={event => editPriority(index, { expectedOutcome: event.target.value })}/></div>)}</div></div>{text("nextPlan", "Main Objective for Tomorrow")}</div><details className="report-priority-details"><summary>Link priorities to tasks / dates</summary><div className="space-y-3">{priorities.map((priority, index) => <div key={index}><h3 className="mb-2 text-sm font-semibold">Priority {index + 1}</h3><div className="report-fields"><label className="sales-field">Linked Task<select value={priority.task ?? ""} onChange={event => editPriority(index, { task: event.target.value || undefined })}><option value="">No linked task</option>{liveSummary.tasks.map(task => <option key={task._id} value={task._id}>{task.taskId} · {task.name}</option>)}{priority.task && !liveSummary.tasks.some(task => task._id === priority.task) && <option value={priority.task}>Previously linked task</option>}</select></label><label className="sales-field">Priority<select value={priority.priority} onChange={event => editPriority(index, { priority: event.target.value as EodPriority["priority"] })}>{["LOW", "MEDIUM", "HIGH", "URGENT"].map(value => <option key={value}>{value}</option>)}</select></label><label className="sales-field">Expected Completion<input type="date" value={priority.expectedCompletion ?? ""} onChange={event => editPriority(index, { expectedCompletion: event.target.value || undefined })}/></label><label className="sales-field">Note<input maxLength={1000} value={priority.note ?? ""} onChange={event => editPriority(index, { note: event.target.value })}/></label></div></div>)}</div></details></ReportCard></div>
    <ReportCard index={6} title={`${number + 3}. Daily Summary`} action={<span className="sales-summary-note">Task totals from MobiusEMS · {update?.status === "SUBMITTED" ? "saved snapshot" : "current records"}</span>}><div className="report-summary">{[["Completed Today", metrics.completed], ["In Progress", metrics.inProgress], ["In Review", metrics.inReview], ["Blocked", metrics.blocked], ["Overdue", metrics.overdue], ["Todos Completed", metrics.todosCompleted]].map(([label, value]) => <label className="sales-field" key={label}>{label}<input readOnly value={value ?? "—"}/></label>)}</div><div className="report-summary-context">{text("accomplishments", "Today's Key Result")}{text("inProgress", "Work Still in Progress")}</div></ReportCard>
    <div className="sales-footer"><label className="sales-field">Additional Remarks (Optional)<input maxLength={4000} value={draft.remarks} onChange={event => edit("remarks", event.target.value)} placeholder="Any additional remarks, learnings or feedback"/></label><div className="flex flex-wrap gap-2">{update?.status !== "SUBMITTED" && <Button type="button" variant="secondary" onClick={() => save.mutate("DRAFT")}><Save size={16} aria-hidden="true"/>Save draft</Button>}<Button type="submit"><Send size={16} aria-hidden="true"/>{save.isPending ? "Saving…" : update?.status === "SUBMITTED" ? "Update EOD Report" : "Submit EOD Report"}</Button></div></div>
    <div className="report-intelligence"><h2><Sparkles size={17} aria-hidden="true"/>{EOD_REPORT_LABELS[template.adapter]} Work Intelligence</h2><ul>{(signals.length ? signals : ["No coordination gaps flagged in the available records. Add context for work tracked elsewhere."]).map(signal => <li key={signal}>{signal}</li>)}</ul><p>Suggestions use entered report context and recorded task status.</p></div>
    <details className="sales-evidence"><summary>Voice input</summary><div className="report-fields"><label className="sales-field">Field to Dictate<select value={voiceField} onChange={event => setVoiceField(event.target.value)}>{voiceFields.map(f => <option key={f.key} value={f.key}>{f.label}</option>)}</select></label><VoiceDictation key={voiceField} disabled={save.isPending || !canSubmit} onTranscript={value => { setSaved(""); if (voiceField.startsWith("response:")) { const key = voiceField.slice(9); setResponses(current => ({ ...current, [key]: `${current[key] ?? ""}\n${value}`.trim().slice(0, 4000) })); } else setDraft(current => ({ ...current, [voiceField]: `${current[voiceField as keyof typeof current]}\n${value}`.trim().slice(0, 4000) })); }}/></div></details>
    <details className="sales-evidence"><summary>System work evidence & previous commitments</summary><p className="mb-4 text-xs text-slate-600">Generated {new Date(summary.generatedAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST. Department counts entered above remain separate from task totals.</p>{template.adapter === "ENGINEERING" && <EngineeringIntelligence summary={summary}/>}<MetricCards metrics={[["Assigned tasks", metrics.totalAssigned], ["Reopened", metrics.reopened], ["Todos pending", metrics.todosPending], ["Quality / 5", metrics.averageQuality], ["On-time %", metrics.onTimePercent], ["Hours variance", metrics.hoursVariance]]}/><p className="my-3 text-xs text-slate-600">Estimated {metrics.estimatedHours ?? 0}h / actual {metrics.actualHours ?? 0}h for completed tasks with recorded hours.</p><h3 className="my-3 font-semibold">Work completed</h3><TaskCards tasks={completed}/><h3 className="my-3 font-semibold">Work in progress</h3><TaskCards tasks={summary.tasks.filter(task => ["NOT_STARTED", "IN_PROGRESS", "REOPENED", "IN_REVIEW"].includes(task.status))}/><h3 className="my-3 font-semibold">Blocked work</h3><TaskCards tasks={summary.tasks.filter(task => task.status === "BLOCKED")}/>{!!liveSummary.commitments.length && <><h3 className="my-3 font-semibold">Previous report commitments</h3><ul className="space-y-2">{liveSummary.commitments.map((p, i) => <li key={i} className="rounded-lg border p-3 text-sm">{p.expectedOutcome} · {p.state.replaceAll("_", " ")}</li>)}</ul></>}{summary.sales && <SalesSnapshot sales={summary.sales}/>}<label className="sales-field mt-4">Reported Tasks Completed (Optional)<input type="number" min={0} max={10000} step={1} value={reportedCompleted} onChange={event => setReportedCompleted(event.target.value)}/></label><p className="mt-2 text-xs text-slate-600">Differences can reflect work outside this system. {template.name} · version {template.version}.</p></details>
  </fieldset>{save.error && <p role="alert" className="sales-error">{save.error.message}</p>}{saved && <p role="status" className="sales-message">{saved}</p>}</form>{update?.acknowledgedAt && <section className="sales-evidence"><h2 className="font-semibold">Manager Review · {(update.review?.state ?? "ACKNOWLEDGED").replaceAll("_", " ")}</h2><p className="mt-2 whitespace-pre-wrap">{update.managerComment || "Your daily update has been acknowledged."}</p></section>}</div>;
}
