import { Activity, ArrowUpRight, CheckCircle2, ShieldAlert, GitPullRequest, Sparkles } from "lucide-react";
import type { EodWorkSummary } from "@mobius-ems/shared";
import { panel } from "./EodComponents";

export function EngineeringIntelligence({ summary }: { summary: EodWorkSummary }) {
  const metrics = summary.metrics;
  const signals = [
    ...(metrics.blocked ? [{ title: "Unblock delivery", text: `${metrics.blocked} task(s) are blocked. Confirm the owner and support needed before planning new work.`, tone: "amber" }] : []),
    ...(metrics.overdue ? [{ title: "Replan overdue work", text: `${metrics.overdue} task(s) are past their deadline. Agree on a revised delivery date.`, tone: "amber" }] : []),
    ...(metrics.inReview ? [{ title: "Review queue", text: `${metrics.inReview} task(s) are waiting for review. Ask for reviewer availability to move delivery forward.`, tone: "blue" }] : []),
    ...(metrics.reopened ? [{ title: "Rework context", text: `${metrics.reopened} task(s) were reopened. Record the cause and verification needed for the next handoff.`, tone: "blue" }] : [])
  ];
  const outcomes = [["Delivered today", metrics.completed, CheckCircle2], ["In development", metrics.inProgress, Activity], ["Ready for review", metrics.inReview, GitPullRequest], ["Needs support", metrics.blocked, ShieldAlert]] as const;
  return <section className={`${panel} overflow-hidden !p-0`}><div className="bg-slate-900 px-5 py-6 text-white sm:px-6"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-blue-200"><Sparkles size={16} aria-hidden="true"/>Engineering intelligence</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-semibold">Turn today’s work into tomorrow’s progress</h2><p className="mt-2 max-w-2xl text-sm text-slate-300">Delivery evidence, decisions, and dependencies in one daily report.</p></div><span className="rounded-lg border border-slate-600 px-3 py-2 text-xs">{summary.date} · IST</span></div></div><div className="p-5 sm:p-6"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{outcomes.map(([label, value, Icon]) => <div key={label} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex justify-between gap-2"><p className="text-xs font-semibold text-slate-600">{label}</p><Icon size={17} className="text-blue-600" aria-hidden="true"/></div><p className="mt-3 text-3xl font-semibold tabular-nums">{value ?? "—"}</p></div>)}</div><h3 className="mt-6 flex items-center gap-2 font-semibold"><ArrowUpRight size={18} aria-hidden="true"/>What needs attention</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{signals.map(signal => <article key={signal.title} className={`rounded-xl border p-4 ${signal.tone === "amber" ? "border-amber-200 bg-amber-50" : "border-blue-200 bg-blue-50"}`}><h4 className="text-sm font-semibold">{signal.title}</h4><p className="mt-2 text-sm text-slate-700">{signal.text}</p></article>)}{!signals.length && <p className="text-sm text-slate-600">No delivery risks flagged in the available task records. Add context for work tracked elsewhere.</p>}</div><p className="mt-4 text-xs text-slate-500">Signals use the displayed task snapshot, generated {new Date(summary.generatedAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST. They support planning and do not measure individual productivity.</p></div></section>;
}
