import type { ReactNode } from "react";
import type { EodField, EodResponseValue, EodTask, EodWorkSummary } from "@mobius-ems/shared";
import { Input } from "@/components/ui/Input";
export const panel = "rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6";
export const control = "mt-2 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm font-normal outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100";
export const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
export const healthLabels = { ON_TRACK: "On track", AT_RISK: "At risk", BLOCKED: "Blocked" };
export function Section({ title, hint, children }: { title: string; hint?: string; children: ReactNode }) {
  return <section className={panel}><h2 className="text-lg font-semibold text-slate-900">{title}</h2>{hint && <p className="mt-1 text-sm text-slate-600">{hint}</p>}<div className="mt-5">{children}</div></section>;
}
export function MetricCards({ metrics }: { metrics: Array<[string, number | null | undefined, string?]> }) {
  return <div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{metrics.map(([label, value, hint]) => <div key={label} className="rounded-xl border bg-white p-4"><p className="text-xs font-semibold text-slate-600">{label}</p><p className="mt-2 text-2xl font-bold tabular-nums text-slate-900">{value == null ? "—" : value.toLocaleString("en-IN")}</p>{hint && <p className="mt-2 text-xs text-slate-600">{hint}</p>}</div>)}</div>;
}
export function TaskCards({ tasks }: { tasks: EodTask[] }) {
  return <div className="grid gap-3 lg:grid-cols-2">{tasks.map(task => <article key={task._id} className="rounded-xl border bg-slate-50 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-xs font-semibold text-brand-700">{task.taskId} · {task.project?.name ?? "Project unavailable"}</p><h3 className="mt-1 font-semibold">{task.name}</h3></div><span className="rounded-lg border bg-white px-2 py-1 text-xs">{task.status.replaceAll("_", " ")}</span></div><p className="mt-2 text-xs text-slate-600">{task.priority} priority · Due {new Date(task.deadline).toLocaleDateString("en-IN", { timeZone: "Asia/Kolkata" })}{task.qualityRating != null ? ` · Quality ${task.qualityRating}/5` : ""}</p>{task.completionNote && <p className="mt-3 whitespace-pre-wrap text-sm text-slate-700">{task.completionNote}</p>}{task.deliverableUrl && /^https?:\/\//i.test(task.deliverableUrl) && <a href={task.deliverableUrl} target="_blank" rel="noreferrer" className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-brand-700 underline">View deliverable</a>}{task.blocker && !task.blocker.resolvedAt && <div className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900"><p className="font-semibold">{task.blocker.reason.replaceAll("_", " ")} · {Math.max(0, Math.floor((Date.now() - Date.parse(task.blocker.startedAt)) / 86400000))} days</p><p className="mt-1 whitespace-pre-wrap">{task.blocker.comment || "No blocker note recorded"}</p></div>}</article>)}{!tasks.length && <p className="text-sm text-slate-600">No system-recorded work in this group.</p>}</div>;
}
export function TemplateField({ field, value, metric, onChange }: { field: EodField; value?: EodResponseValue; metric?: number | null; onChange: (value: EodResponseValue) => void }) {
  if (field.source) return <div className="rounded-xl bg-brand-50 p-4"><p className="text-sm font-semibold">{field.label}</p><p className="mt-2 text-xl font-bold">{metric ?? "Unavailable"}</p><p className="mt-1 text-xs text-slate-600">System-generated · {field.source}</p></div>;
  const id = `eod-field-${field.key}`;
  return <div><label htmlFor={id} className="block text-sm font-semibold">{field.label}{field.required ? " *" : ""}<span className="ml-2 text-xs font-normal text-slate-500">Manual context</span></label>{field.type === "TEXTAREA" ? <textarea id={id} className={control} rows={3} maxLength={4000} value={typeof value === "string" ? value : ""} onChange={event => onChange(event.target.value)}/> : field.type === "SELECT" || field.type === "MULTI_SELECT" ? <select id={id} className={control} multiple={field.type === "MULTI_SELECT"} value={field.type === "MULTI_SELECT" ? Array.isArray(value) ? value : [] : typeof value === "string" ? value : ""} onChange={event => onChange(field.type === "MULTI_SELECT" ? Array.from(event.target.selectedOptions, o => o.value) : event.target.value)}>{field.type === "SELECT" && <option value="">Choose if relevant</option>}{field.options?.map(option => <option key={option}>{option}</option>)}</select> : field.type === "CHECKBOX" ? <input id={id} type="checkbox" className="mt-2 size-6 accent-brand-600" checked={value === true} onChange={event => onChange(event.target.checked)}/> : <Input id={id} className="mt-2" type={["NUMBER", "CURRENCY", "RATING"].includes(field.type) ? "number" : field.type === "DATE" ? "date" : "text"} min={field.type === "RATING" ? 1 : undefined} max={field.type === "RATING" ? 5 : undefined} step={field.type === "RATING" ? 1 : "any"} maxLength={4000} value={typeof value === "string" || typeof value === "number" ? value : ""} onChange={event => onChange(["NUMBER", "CURRENCY", "RATING"].includes(field.type) && event.target.value !== "" ? Number(event.target.value) : event.target.value)}/>}</div>;
}
export const metricForSource = (source: EodField["source"], summary: EodWorkSummary) => {
  const mapping: Record<string, string> = { TASKS_COMPLETED_TODAY: "completed", TASKS_IN_PROGRESS: "inProgress", TASKS_BLOCKED: "blocked", TASKS_IN_REVIEW: "inReview", TASKS_REOPENED: "reopened", TASKS_OVERDUE: "overdue", DAILY_TODOS_COMPLETED: "todosCompleted", SALES_LEADS_CONTACTED: "leadsContacted", SALES_QUALIFIED_LEADS: "qualifiedLeads", SALES_FOLLOWUPS_COMPLETED: "followupsCompleted", SALES_MEETINGS: "meetings", SALES_REVENUE_COLLECTED: "revenueCollected" };
  if (["SALES_PIPELINE_ADDED", "SALES_REVENUE_BOOKED"].includes(source ?? "")) { const values = Object.values(summary.sales?.money ?? {}); return values.length === 1 ? source === "SALES_PIPELINE_ADDED" ? values[0].pipelineAdded : values[0].revenueBooked : null; }
  return source?.startsWith("SALES_") ? summary.sales?.metrics[mapping[source]] : summary.metrics[mapping[source ?? ""]];
};
export function SalesSnapshot({ sales }: { sales: NonNullable<EodWorkSummary["sales"]> }) {
  return <div className="space-y-4"><MetricCards metrics={[["Leads contacted", sales.metrics.leadsContacted], ["Qualified leads", sales.metrics.qualifiedLeads], ["Meetings / demos", sales.metrics.meetings], ["Follow-ups completed", sales.metrics.followupsCompleted], ["Overdue follow-ups", sales.metrics.overdueFollowups], ["Opportunities created", sales.metrics.opportunitiesCreated]]}/>{Object.entries(sales.money).map(([currency, value]) => <div key={currency} className="rounded-xl bg-slate-50 p-4"><h3 className="mb-3 font-semibold">{currency} · CRM-derived values</h3><MetricCards metrics={[["Pipeline added", value.pipelineAdded], ["Won deal value", value.revenueBooked], ["Revenue recorded", value.revenueRecorded], ["Active target", value.target], ["Target achievement %", value.target ? Math.round(value.targetRevenueRecorded / value.target * 100) : null, "Full target period to selected date"], ["Revenue collected", null, "Collection state unavailable"]]}/></div>)}{sales.hotOpportunities.length > 0 && <details><summary className="min-h-11 cursor-pointer text-sm font-semibold">Hot opportunities ({sales.hotOpportunities.length})</summary><ul className="space-y-2 text-sm">{sales.hotOpportunities.map(o => <li key={o._id} className="rounded-lg border p-3">{o.name} · {o.currency} {o.estimatedValue.toLocaleString()} · {o.probability}% probability</li>)}</ul></details>}</div>;
}
