import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Plus, Trash2, Send, Save } from "lucide-react";
import { SALES_EOD_SECTIONS, SALES_FOLLOWUP_STATUSES, readSalesFollowups, salesNumber, type EodField, type EodResponseValue, type SalesFollowup } from "@mobius-ems/shared";
import { api } from "@/api/client";
import { Button } from "@/components/ui/Button";
import { VoiceDictation } from "@/components/VoiceDictation";
import type { MyReportData } from "./EmployeeReport";
import { SalesSnapshot } from "./EodComponents";
import { ReportCard as Card, ReportBasicInformation } from "./ReportLayout";

const blankRow = (): SalesFollowup => ({ name: "", status: "", nextAction: "", expectedValue: 0, expectedDate: "" });
export function SalesReport({ date, data, canSubmit }: { date: string; data: MyReportData; canSubmit: boolean }) {
  const client = useQueryClient();
  const { update, summary, template } = data;
  const [values, setValues] = useState<Record<string, EodResponseValue>>(update?.responses ?? {});
  const [rows, setRows] = useState<SalesFollowup[]>(() => { const saved = readSalesFollowups(update?.responses?.importantFollowups); return saved.length ? saved : [blankRow(), blankRow(), blankRow()]; });
  const [remarks, setRemarks] = useState(update?.remarks ?? "");
  const [message, setMessage] = useState("");
  const [voiceField, setVoiceField] = useState("keyResult");
  const set = (key: string, value: EodResponseValue) => { setMessage(""); setValues(current => ({ ...current, [key]: value })); };
  const num = (key: string) => salesNumber(values, key);
  const rowChange = (index: number, patch: Partial<SalesFollowup>) => { setMessage(""); setRows(current => current.map((row, i) => i === index ? { ...row, ...patch } : row)); };
  const save = useMutation({ mutationFn: (status: "DRAFT" | "SUBMITTED") => {
    const populated = rows.filter(r => r.name.trim() || r.status || r.nextAction.trim() || r.expectedValue || r.expectedDate);
    if (populated.some(r => !r.name.trim())) throw new Error("Add a customer / lead name to each populated follow-up row.");
    const serialized = JSON.stringify(populated);
    if (serialized.length > 4000) throw new Error("Follow-up details are too long. Shorten the notes before saving.");
    if (status === "SUBMITTED" && num("dealsClosed") > 0 && !String(values.customerNames ?? "").trim()) throw new Error("Deals closed > 0 — add customer name(s).");
    if (status === "SUBMITTED" && num("dealsClosed") > 0 && !num("revenueBooked") && !num("salesClosed")) throw new Error("Deals closed but revenue is ₹0 — check the figures.");
    const blockers = ["objections", "productDoubts", "pricingIssues", "supportRequired"].map(key => values[key]).filter(Boolean).join("\n");
    const priorities = ["priority1", "priority2", "priority3"].map(key => String(values[key] ?? "").trim()).filter(Boolean).map(expectedOutcome => ({ expectedOutcome, priority: "HIGH" }));
    return api.put("/api/v1/eod", { date, status, responses: { ...Object.fromEntries(SALES_EOD_SECTIONS.flatMap(s => s.fields).filter(f => ["NUMBER", "CURRENCY"].includes(f.type)).map(f => [f.key, num(f.key)])), ...values, importantFollowups: serialized }, remarks, accomplishments: String(values.keyResult || `${num("dealsClosed")} deals closed; ${num("qualifiedLeads")} qualified leads; ${num("demosCompleted")} demos completed.`), inProgress: "", nextPlan: String(values.mainObjective || `Sales target: INR ${num("tomorrowTarget")}; demos / meetings: ${num("tomorrowDemos")}; expected closures: INR ${num("tomorrowClosures")}.`), blockers: blockers.slice(0, 4000), health: blockers ? "AT_RISK" : "ON_TRACK", priorities });
  }, onSuccess: async (_, status) => { setMessage(status === "DRAFT" ? "Draft saved. Only you can see it." : "Sales EOD report submitted successfully."); await client.invalidateQueries({ queryKey: ["eod"] }); } });
  const selectedProducts = (key: string): string[] => { const value = values[key]; return Array.isArray(value) ? value : []; };
  const field = (f: EodField) => f.type === "MULTI_SELECT" ? <fieldset key={f.key} className="sales-field"><legend>{f.label}</legend><div className="sales-products">{f.options?.map(product => <label key={product}><input type="checkbox" checked={selectedProducts(f.key).includes(product)} onChange={e => set(f.key, e.target.checked ? [...selectedProducts(f.key), product] : selectedProducts(f.key).filter(p => p !== product))}/>{product}</label>)}</div></fieldset> : <label key={f.key} className="sales-field">{f.label}{f.type === "TEXTAREA" ? <textarea rows={3} maxLength={4000} value={String(values[f.key] ?? "")} onChange={e => set(f.key, e.target.value)} placeholder={`Enter ${f.label.toLowerCase()}`}/> : <input type={f.type === "DATE" ? "date" : ["NUMBER", "CURRENCY"].includes(f.type) ? "number" : "text"} min={0} max={1e12} step={f.type === "NUMBER" ? 1 : "any"} maxLength={f.key.startsWith("priority") ? 500 : 4000} value={String(values[f.key] ?? (["NUMBER", "CURRENCY"].includes(f.type) ? 0 : ""))} onChange={e => set(f.key, ["NUMBER", "CURRENCY"].includes(f.type) && e.target.value ? Number(e.target.value) : e.target.value)}/>}</label>;
  const tomorrowSection = <Card index={5} title="6. Tomorrow's Plan"><div className="sales-tomorrow-targets">{SALES_EOD_SECTIONS[5].fields.slice(0, 3).map(field)}</div><div className="sales-tomorrow-plan"><div><h3 className="mb-2 text-sm font-medium">Priority Leads (Top 3)</h3><div className="sales-priorities">{SALES_EOD_SECTIONS[5].fields.slice(3, 6).map((f, i) => <div key={f.key}><span>{i + 1}.</span><input aria-label={f.label} maxLength={500} value={String(values[f.key] ?? "")} placeholder="Enter lead name" onChange={e => set(f.key, e.target.value)}/></div>)}</div></div>{field(SALES_EOD_SECTIONS[5].fields[6])}</div></Card>;
  const section = (index: number) => <Card index={index} title={SALES_EOD_SECTIONS[index].title}><div className={`sales-fields sales-fields-${index}`}>{SALES_EOD_SECTIONS[index].fields.map(field)}</div></Card>;
  return <div className="sales-report"><form onSubmit={e => { e.preventDefault(); save.mutate("SUBMITTED"); }}><fieldset disabled={!canSubmit || save.isPending}>
    <ReportBasicInformation date={date} data={data}/>
    <div className="sales-pair">{section(0)}{section(1)}</div>{section(2)}
    <Card index={3} title="4. Important Follow-ups" action={<Button type="button" disabled={rows.length >= 12} onClick={() => { setMessage(""); setRows([...rows, blankRow()]); }}><Plus size={16} aria-hidden="true"/>Add Row</Button>}><div className="sales-table-wrap"><table><thead><tr>{["#", "Customer / Lead Name", "Current Status", "Next Action", "Expected Value (₹)", "Expected Date", ""].map((h, i) => <th key={i} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}><td>{i + 1}</td><td><input aria-label={`Follow-up ${i + 1} customer / lead name`} maxLength={120} value={row.name} onChange={e => rowChange(i, { name: e.target.value })} placeholder="Enter name"/></td><td><select aria-label={`Follow-up ${i + 1} status`} value={row.status} onChange={e => rowChange(i, { status: e.target.value })}><option value="">Select status</option>{SALES_FOLLOWUP_STATUSES.map(s => <option key={s}>{s}</option>)}</select></td><td><input aria-label={`Follow-up ${i + 1} next action`} maxLength={200} value={row.nextAction} onChange={e => rowChange(i, { nextAction: e.target.value })} placeholder="Enter next action"/></td><td><input aria-label={`Follow-up ${i + 1} expected value`} type="number" min={0} max={1e12} step="any" value={row.expectedValue} onChange={e => rowChange(i, { expectedValue: Number(e.target.value) })}/></td><td><input aria-label={`Follow-up ${i + 1} expected date`} type="date" value={row.expectedDate} onChange={e => rowChange(i, { expectedDate: e.target.value })}/></td><td><button className="sales-remove" type="button" disabled={rows.length === 1} aria-label={`Remove follow-up ${i + 1}`} onClick={() => setRows(rows.filter((_, index) => i !== index))}><Trash2 size={16} aria-hidden="true"/></button></td></tr>)}</tbody></table></div></Card>
    <div className="sales-pair">{section(4)}{tomorrowSection}</div>
    <Card index={6} title="7. Daily Summary" action={<span className="sales-summary-note">Auto-calculated from sections 1–2</span>}><div className="sales-summary">{[["Revenue (₹)", num("revenueBooked") || num("salesClosed")], ["Deals Closed", num("dealsClosed")], ["Qualified Leads", num("qualifiedLeads")], ["Pipeline Added (₹)", num("pipelineValue")], ["Demos", num("demosCompleted")]].map(([label, value]) => <label className="sales-field" key={label}>{label}<input readOnly value={Number(value).toLocaleString("en-IN")}/></label>)}{field(SALES_EOD_SECTIONS[6].fields[0])}</div></Card>
    <div className="sales-footer"><label className="sales-field">Additional Remarks (Optional)<input maxLength={4000} value={remarks} onChange={e => setRemarks(e.target.value)} placeholder="Any additional remarks, learnings or feedback"/></label><div className="flex flex-wrap gap-2">{update?.status !== "SUBMITTED" && <Button variant="secondary" type="button" onClick={() => save.mutate("DRAFT")}><Save size={16} aria-hidden="true"/>Save draft</Button>}<Button type="submit"><Send size={16} aria-hidden="true"/>{save.isPending ? "Saving…" : update?.status === "SUBMITTED" ? "Update EOD Report" : "Submit EOD Report"}</Button></div></div>
    <details className="sales-evidence"><summary>Voice input & sales intelligence</summary><div className="sales-fields"><label className="sales-field">Field to dictate<select value={voiceField} onChange={e => setVoiceField(e.target.value)}>{SALES_EOD_SECTIONS.flatMap(s => s.fields).filter(f => ["TEXT", "TEXTAREA"].includes(f.type) && f.key !== "importantFollowups").map(f => <option key={f.key} value={f.key}>{f.label}</option>)}</select></label><VoiceDictation key={voiceField} disabled={!canSubmit || save.isPending} onTranscript={text => set(voiceField, `${values[voiceField] ?? ""}\n${text}`.trim().slice(0, 4000))}/></div><SalesSignals values={values} rows={rows} date={date}/>{summary.sales && <div className="mt-5"><h3 className="mb-3 font-semibold">CRM evidence · separate from reported figures</h3><SalesSnapshot sales={summary.sales}/></div>}<p className="mt-3 text-xs text-slate-600">{template.name} · version {template.version}. Reported amounts use INR. CRM evidence keeps its original currencies.</p></details>
  </fieldset>{save.error && <p className="sales-error" role="alert">{save.error.message}</p>}{message && <p className="sales-message" role="status">{message}</p>}</form>{update?.managerComment && <div className="sales-evidence"><h2 className="font-semibold">Manager feedback</h2><p className="mt-2 whitespace-pre-wrap">{update.managerComment}</p></div>}</div>;
}
function SalesSignals({ values, rows, date }: { values: Record<string, EodResponseValue>; rows: SalesFollowup[]; date: string }) {
  const overdue = rows.filter(r => r.name && r.expectedDate && r.expectedDate < date && !["Won", "Lost"].includes(r.status));
  const missing = rows.filter(r => r.name && !["Won", "Lost"].includes(r.status) && (!r.nextAction || !r.expectedDate));
  const signals = [...(overdue.length ? [`${overdue.length} reported follow-up(s) are past the expected date. Reconfirm the next action.`] : []), ...(missing.length ? [`${missing.length} open follow-up(s) need a next action or expected date.`] : []), ...(salesNumber(values, "hotLeads") > 0 && !values.expectedClosingDate ? ["Hot leads reported: add an expected closing date to help plan support."] : []), ...(salesNumber(values, "tomorrowClosures") > salesNumber(values, "pipelineValue") ? ["Tomorrow’s expected closures exceed today’s reported pipeline value. Confirm the opportunity context."] : [])];
  return <div className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4"><h3 className="font-semibold">Sales intelligence</h3><p className="mt-1 text-xs text-slate-600">Rules based on your report entries; check customer context before acting.</p><ul className="mt-3 space-y-2 text-sm">{(signals.length ? signals : ["No follow-up gaps detected in the entered report. Review customer commitments before submitting."]).map(s => <li key={s}>{s}</li>)}</ul></div>;
}
