import assert from 'node:assert/strict';
import pg from 'pg';
import nodemailer from 'nodemailer';
if (!process.env.AUDIT_DATABASE_URL) throw new Error('Set AUDIT_DATABASE_URL to run the isolated PostgreSQL integration audit');
const schema=`mobius_quality_${Date.now()}`;
assert.match(schema,/^mobius_quality_\d+$/);
const sourceUrl=process.env.AUDIT_DATABASE_URL;
const administrator=new pg.Client({connectionString:sourceUrl,ssl:process.env.AUDIT_DATABASE_SSL === 'true' ? {rejectUnauthorized:false} : undefined});
await administrator.connect();
const testUrl=new URL(sourceUrl);
testUrl.searchParams.set('options',`-c search_path=${schema}`);
Object.assign(process.env,{DATABASE_URL:testUrl.toString(),POSTGRES_SSL:process.env.AUDIT_DATABASE_SSL === 'true' ? 'true' : 'false',POSTGRES_MAX_POOL_SIZE:'3',NODE_ENV:'test',JWT_ACCESS_SECRET:'isolated-integration-access-secret',JWT_REFRESH_SECRET:'isolated-integration-refresh-secret',PLATFORM_ADMIN_EMAILS:'',PLATFORM_OWNER_EMAIL:'owner@audit.example',PLATFORM_OWNER_PASSWORD:'AuditOwner!Password2026',SUPER_ADMIN_EMAIL:'admin@audit.example',SUPER_ADMIN_PASSWORD:'AuditAdmin!Password2026',DEFAULT_TENANT_SLUG:'audit-default',DEFAULT_TENANT_NAME:'Audit Default',SMTP_HOST:'smtp.audit.example',SMTP_USER:'sender@audit.example',SMTP_PASSWORD:'mock-only',BREVO_API_KEY:'',EMAIL_AUTOMATION_ENABLED:'false',WHALEXY_DEMO_ENABLED:'false',WHALEXY_DEMO_PASSWORD:'IsolatedDemo!Password2026',CLIENT_URL:'http://127.0.0.1',COOKIE_DOMAIN:''});
const mails=[];
process.env.NODE_ENV='development';
delete process.env.BREVO_API_KEY;
nodemailer.createTransport=()=>({sendMail:async message=>{mails.push(message);return {messageId:'isolated-mock'};},close:()=>{}});
let pool,server;
const results=[];
const passed=name=>{results.push({name,passed:true});console.log('PASS '+name);};
try{
 await administrator.query(`CREATE SCHEMA "${schema}"`);
 const {postgres,connectPostgres}=await import('../dist/persistence/postgres.js');
 pool=postgres;
 assert.equal((await pool.query('SELECT current_schema() AS name')).rows[0].name,schema);
 await connectPostgres();
 await import('../dist/tenancy/modelRegistry.js');
 const {createApp}=await import('../dist/app.js');
 const {synchronizePostgresModels}=await import('../dist/persistence/postgresModel.js');
 console.log('Initializing isolated test tables');
 await synchronizePostgresModels();
 server=createApp().listen(0,'127.0.0.1');
 await new Promise(resolve=>server.once('listening',resolve));
 const origin=`http://127.0.0.1:${server.address().port}`;
 const request=async(method,path,body,cookie,expected=200)=>{
  const response=await fetch(origin+'/api/v1'+path,{method,headers:{'content-type':'application/json',...(cookie?{cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});
  const data=await response.json();
  assert.equal(response.status,expected,`${method} ${path}: ${data.message}`);
  return {data,cookie:response.headers.getSetCookie().map(value=>value.split(';')[0]).join('; ')};
 };
 const details={name:'Quality Audit One',slug:'quality-audit-one',industry:'Software',companySize:'1-10',country:'India',referralSource:'Website',primaryUseCase:'HR management',adminName:'Audit Administrator',adminEmail:'admin-one@audit.example'};
 const initial=await request('POST','/registration/request',details);
 assert.equal(initial.data.data.emailSent,true);
 const otp=mails.at(-1).subject.match(/\d{6}/)[0];
 const registrationToken=initial.data.data.registrationToken;
 const password='AuditAdmin!Password2026';
 await request('POST','/registration/complete',{token:registrationToken,password},undefined,400);
 await request('POST','/registration/verify-otp',{registrationToken,otp:otp==='111111'?'222222':'111111',password},undefined,400);
 await request('POST','/registration/verify-otp',{registrationToken,otp,password},undefined,201);
 passed('Email verification rejects bypass and wrong OTP, creates an organization with the correct OTP');
 await request('POST','/registration/request',details,undefined,409);
 passed('Duplicate administrator registration is rejected');
 const admin=await request('POST','/auth/login',{email:details.adminEmail,password});
 const cookie=admin.cookie;
 assert.ok(cookie.includes('access_token='));
 await request('GET','/auth/me',undefined,cookie);
 passed('Email-only login and authenticated session');
 await request('POST','/auth/login',{email:details.adminEmail,password:'InvalidPassword!2026'},undefined,401);
 await request('GET','/employees',undefined,undefined,401);
 passed('Wrong password and anonymous employee access are rejected');
 const {Tenant}=await import('../dist/models/Tenant.js');
 const {Department}=await import('../dist/models/Department.js');
 const {Designation}=await import('../dist/models/Designation.js');
 const {User}=await import('../dist/models/User.js');
 const {runWithTenant}=await import('../dist/tenancy/tenantContext.js');
 const tenant=await Tenant.findOne({slug:details.slug});
 const refs=await runWithTenant(tenant._id,async()=>({department:await Department.findOne(),designation:await Designation.findOne()}));
 const employeeInput={employeeId:'AUDIT001',firstName:'Audit',lastName:'Employee',officialEmail:'employee@audit.example',department:String(refs.department._id),designation:String(refs.designation._id),dateOfJoining:'2026-01-01',employmentType:'FULL_TIME',role:'EMPLOYEE',status:'ACTIVE'};
 const employee=await request('POST','/employees',employeeInput,cookie,201);
 const employeeId=employee.data.data.employee._id;
 const employeePassword=employee.data.data.temporaryCredentials.password;
 const employeeSession=await request('POST','/auth/login',{email:employeeInput.officialEmail,password:employeePassword});
 await request('PATCH',`/employees/${employeeId}`,{phone:'9876543210'},cookie);
 await request('GET',`/employees/${employeeId}`,undefined,cookie);
 await request('POST','/employees',{...employeeInput,employeeId:'AUDIT002',officialEmail:'other@audit.example'},employeeSession.cookie,403);
 passed('Employee create, edit, profile, credentials, and role enforcement');
 const hash=await runWithTenant(tenant._id,()=>User.findOne({email:employeeInput.officialEmail}).select('+passwordHash'));
 assert.ok(hash.passwordHash);
 passed('Employee updates preserve credentials');
 const todo=await request('POST','/todos',{date:'2026-10-01',title:'Isolated audit task'},employeeSession.cookie,201);
 const todoId=todo.data.data.item._id;
 await request('PATCH',`/todos/${todoId}`,{completed:true},employeeSession.cookie);
 await request('DELETE',`/todos/${todoId}`,undefined,employeeSession.cookie);
 passed('Personal todo create, complete, and delete');
 await request('POST','/auth/forgot-password',{email:details.adminEmail});
 const resetLink=new URL(mails.at(-1).text.match(/https?:\/\/\S+/)[0]);
 const token=resetLink.searchParams.get('token');
 assert.ok(token);
 const newPassword='ChangedAudit!Password2026';
 await request('POST','/auth/reset-password',{email:details.adminEmail,token,newPassword});
 await request('POST','/auth/reset-password',{email:details.adminEmail,token,newPassword},undefined,400);
 await request('POST','/auth/login',{email:details.adminEmail,password:newPassword});
 passed('Email-only password recovery, reset, and token replay rejection');
 const {createTenant}=await import('../dist/services/tenantService.js');
 const other=await createTenant({name:'Quality Audit Two',slug:'quality-audit-two',plan:'STANDARD',adminName:'Other Administrator',adminEmail:'admin-two@audit.example',temporaryPassword:password});
 const otherSession=await request('POST','/auth/login',{email:'admin-two@audit.example',password});
 await request('GET',`/employees/${employeeId}`,undefined,otherSession.cookie,404);
 await request('PATCH',`/employees/${employeeId}`,{firstName:'Forbidden'},otherSession.cookie,404);
 assert.notEqual(String(other._id),String(tenant._id));
 passed('Cross-tenant profile reads and writes are blocked');
 const loginAgain=await request('POST','/auth/login',{email:details.adminEmail,password:newPassword});
 const refreshed=await request('POST','/auth/refresh',undefined,loginAgain.cookie);
 await request('POST','/auth/logout',undefined,refreshed.cookie);
 await request('POST','/auth/refresh',undefined,refreshed.cookie,401);
 passed('Session refresh and logout revocation');
 await request('POST','/platform/auth/login',{email:'owner@audit.example',password:'AuditOwner!Password2026'});
 passed('Separate platform-owner login');
 console.log(JSON.stringify({passed:results.length,schema,mailDispatch:'mocked; no external messages'}));
}finally{
 if(server)await new Promise(resolve=>server.close(resolve));
 if(pool)await pool.end();
 // Exact generated schema only. Production public tables are never in search_path.
 await administrator.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
 await administrator.end();
 console.log('Isolated schema cleaned up');
}
