export const EOD_FIELD_TYPES = ["TEXT", "TEXTAREA", "NUMBER", "CURRENCY", "DATE", "SELECT", "MULTI_SELECT", "CHECKBOX", "RATING"] as const;
export const EOD_DATA_SOURCES = ["TASKS_COMPLETED_TODAY", "TASKS_IN_PROGRESS", "TASKS_BLOCKED", "TASKS_IN_REVIEW", "TASKS_REOPENED", "TASKS_OVERDUE", "DAILY_TODOS_COMPLETED", "SALES_LEADS_CONTACTED", "SALES_QUALIFIED_LEADS", "SALES_FOLLOWUPS_COMPLETED", "SALES_MEETINGS", "SALES_PIPELINE_ADDED", "SALES_REVENUE_BOOKED", "SALES_REVENUE_COLLECTED"] as const;
export type EodResponseValue = string | number | boolean | string[];
export interface EodField { key: string; label: string; type: typeof EOD_FIELD_TYPES[number]; required?: boolean; options?: string[]; source?: typeof EOD_DATA_SOURCES[number] }
export interface EodSection { key: string; title: string; fields: EodField[] }
export const EOD_ADAPTERS = ["GENERAL", "ENGINEERING", "SALES", "AI_ML", "HR", "MARKETING", "OPERATIONS", "FINANCE", "ADMINISTRATION", "SUPPORT", "DESIGN"] as const;
export interface EodTemplateDefinition { name: string; version: number; sections: EodSection[]; adapter: typeof EOD_ADAPTERS[number]; _id?: string; department?: string; designation?: string; isDefault?: boolean; isActive?: boolean }
export interface EodPriority { task?: string; priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT"; expectedOutcome: string; expectedCompletion?: string; note?: string }
export interface EodContext { _id: string; employeeId: string; firstName: string; lastName: string; department?: { _id: string; name: string; capabilities?: string[] }; designation?: { _id: string; name: string }; team?: { _id: string; name: string }; reportingManager?: { _id: string; firstName: string; lastName: string }; dateOfJoining?: string }
export interface EodTask { _id: string; taskId: string; name: string; assignedEmployee: string; department: string; project: { _id: string; name: string }; status: string; priority: string; deadline: string; completionDate?: string; completionNote?: string; deliverableUrl?: string; qualityRating?: number; estimatedHours: number; actualHours?: number; reopenCount: number; blocker?: { reason: string; comment?: string; startedAt: string; resolvedAt?: string } }
export interface EodWorkSummary { generatedAt: string; date: string; metrics: Record<string, number | null>; tasks: EodTask[]; completedTaskIds?: string[]; sales?: { metrics: Record<string, number | null>; money: Record<string, { pipelineAdded: number; revenueBooked: number; revenueRecorded: number; target: number; targetRevenueRecorded: number }>; hotOpportunities: Array<{ _id: string; name: string; probability: number; estimatedValue: number; currency: string }> }; commitments: Array<EodPriority & { state: "COMPLETED" | "CARRIED_FORWARD" | "PENDING" | "NEWLY_BLOCKED" }> }
export interface EodRecord { _id: string; employee: string; date: string; accomplishments: string; inProgress: string; nextPlan: string; blockers: string; importantNote?: string; remarks?: string; health: "ON_TRACK" | "AT_RISK" | "BLOCKED"; status: "DRAFT" | "SUBMITTED"; submittedAt?: string; acknowledgedAt?: string; managerComment?: string; review?: { state: "ACKNOWLEDGED" | "FEEDBACK" | "NEEDS_CLARIFICATION" | "SUPPORT_REQUIRED"; comment: string }; responses?: Record<string, EodResponseValue>; priorities?: EodPriority[]; templateSnapshot?: EodTemplateDefinition; departmentSnapshot?: { id: string; name: string }; designationSnapshot?: { id: string; name: string }; teamSnapshot?: { id: string; name: string }; reportingManagerSnapshot?: { id: string; name: string }; systemSummary?: EodWorkSummary; reportedCompleted?: number | null }
export interface EodAnalytics { scope: string; period: { start: string; end: string }; overview: Record<string, number | null>; comparison: { submissionPercentagePoints: number; tasksCompleted: number }; trend: Array<{ date: string; eligible: number; submitted: number; submissionPercent: number; completed: number; blocked: number; atRisk: number; blockersCreated: number; blockersResolved: number; overdue: number | null; reviewBacklog: number | null }>; departments: Array<{ id: string; name: string; eligible: number; submitted: number; submissionPercent: number; completed: number; blocked: number; reviewsPending: number; activity: Record<string, number> }>; blockers: { active: number; created: number; resolved: number; averageAgeDays: number; longestAgeDays: number; byReason: Record<string, number>; byDepartment: Record<string, number>; byProject: Record<string, number> }; alerts: Array<{ kind: string; message: string; employee?: string; task?: string }>; employees: EodContext[]; updates: EodRecord[]; tasks: EodTask[]; execution: Record<string, number | null>; sales?: EodWorkSummary["sales"] }
